listener 1883

allow_anonymous true

persistence true
persistence_location /mosquitto/data/

autosave_interval 30

log_dest stdout

max_queued_messages 10000
max_inflight_messages 100


#
# SMOOTHWAVE BRIDGE
#


connection smoothwave

address mqtt.smoothwave.com.ar:1883

remote_username customer1
remote_password MOSca3004

topic device/telemetry out 0
topic tenant1/obd_data out 0

try_private false
start_type automatic
cleansession true
notifications false


keepalive_interval 60
restart_timeout 5
