services:

  # 🟢 MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    networks:
      - iot_net

    restart: unless-stopped
  # 🔴 Redpanda (Kafka API)
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - iot_net
    restart: unless-stopped

  # 🔁 Redpanda Connect (MQTT → Kafka)
  connect:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: redpanda-connect
    depends_on:
      - redpanda
      - mosquitto
    volumes:
      - ./connect/config.yaml:/connect.yaml
    command: ["run", "/connect.yaml"]
    networks:
      - iot_net
    restart: unless-stopped

  # 🟢 PostgreSQL + PostGIS
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iot_net
    restart: unless-stopped

  # 📈 VictoriaMetrics
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    ports:
      - "8428:8428"
    command:
      - "--storageDataPath=/storage"
    volumes:
      - vm_data:/storage
    networks:
      - iot_net
    restart: unless-stopped

  # 🟡 Backend Node.js
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - redpanda
      - postgres
      - victoriametrics
    environment:
      KAFKA_BROKER: redpanda:9092
      PG_HOST: postgres
      PG_USER: iot
      PG_PASSWORD: iot123
      PG_DB: iot
      VM_URL: http://victoriametrics:8428
    ports:
      - "3000:3000"
    networks:
      - iot_net
    restart: unless-stopped

# 🔗 Red interna
networks:
  iot_net:

# 💾 Persistencia
volumes:
  postgres_data:
  redpanda_data:
  vm_data:
